# Generated by Django 2.2.6 on 2019-11-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile_Col',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numCol', models.IntegerField(null=True)),
                ('id_csvFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.CsvFile')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo', models.IntegerField()),
                ('valor', models.FloatField()),
                ('id_csvFile_Col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.CsvFile_Col')),
            ],
        ),
        migrations.AddField(
            model_name='csvfile',
            name='id_experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Experiment'),
        ),
        migrations.CreateModel(
            name='Coordenate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntoX', models.FloatField()),
                ('puntoY', models.FloatField()),
                ('id_csvFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.CsvFile')),
            ],
        ),
    ]
