# Generated by Django 2.2.6 on 2019-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='tiempo',
            field=models.IntegerField(null=True),
        ),
    ]
